# Generated by Django 2.0.5 on 2018-06-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_message_datetime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
