# Generated by Django 2.0.5 on 2018-06-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_textmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
