# Generated by Django 2.0.5 on 2018-06-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('chat', '0012_auto_20180627_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='base',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_text_messages', to='chat.Chat'),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_text_messages', to='signup.Users'),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_text_messages', to='signup.Users'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
