# Generated by Django 2.0.5 on 2018-06-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20180627_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='datetime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
