# Generated by Django 2.0.5 on 2018-07-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_users_last_message_datetime'),
        ('chat', '0015_textmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='is_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='origin_publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_published_text_messages', to='signup.Users'),
        ),
    ]
